# Generated by Django 4.2.6 on 2024-09-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0004_alter_quarterdata_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('graph', 'graph'), ('card', 'card')], max_length=50)),
                ('html', models.TextField()),
                ('js', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('green', 'green'), ('blue', 'blue'), ('red', 'red')], max_length=50)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('for_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashBoard', to='DashBoard.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashBoard.row')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='Base.indicator')),
            ],
        ),
    ]
