# Generated by Django 4.2.6 on 2024-09-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0005_alter_component_category_alter_dashboard_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardindicator',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='DashBoard.component'),
        ),
    ]
