# Generated by Django 4.2.6 on 2024-09-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_quarterdata_indicator'),
        ('DashBoard', '0006_alter_dashboard_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_multiple',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('graph', 'graph'), ('card', 'card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('red', 'red'), ('green', 'green')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='dashboardindicator',
            name='indicator',
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='indicator',
            field=models.ManyToManyField(related_name='indicator', to='Base.indicator'),
        ),
    ]
