# Generated by Django 4.2.6 on 2024-09-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0009_remove_component_html_remove_component_js_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('graph', 'graph'), ('card', 'card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='dashboardindicator',
            name='component',
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='component',
            field=models.ManyToManyField(to='DashBoard.component'),
        ),
    ]
