# Generated by Django 4.2.6 on 2024-09-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0010_alter_component_category_alter_dashboard_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='dashboardindicator',
            name='component',
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component', to='DashBoard.component'),
        ),
    ]
