# Generated by Django 4.2.6 on 2024-09-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0011_alter_dashboard_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('graph', 'graph')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=50),
        ),
    ]
