# Generated by Django 4.2.6 on 2024-09-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0013_alter_component_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='configuration',
            field=models.JSONField(blank=True, default={'key': 'value'}, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=50),
        ),
    ]
