# Generated by Django 4.2.6 on 2024-09-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0017_alter_component_category_alter_dashboard_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red'), ('blue', 'blue')], max_length=50),
        ),
    ]
