# Generated by Django 4.2.6 on 2024-09-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0018_alter_component_configuration_alter_dashboard_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('red', 'red'), ('green', 'green')], max_length=50),
        ),
    ]
