# Generated by Django 4.2.6 on 2024-09-23 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_quarterdata_indicator'),
        ('DashBoard', '0019_alter_dashboard_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='data_range_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='data_range_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='data_type',
            field=models.CharField(choices=[('year', 'year'), ('month', 'month'), ('quarter', 'quarter')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='is_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.datapoint'),
        ),
        migrations.AlterField(
            model_name='component',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('blue', 'blue'), ('red', 'red')], max_length=50),
        ),
    ]
