# Generated by Django 4.2.6 on 2024-09-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_quarterdata_indicator'),
        ('DashBoard', '0020_component_data_range_end_component_data_range_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='data_range_end',
        ),
        migrations.RemoveField(
            model_name='component',
            name='data_range_start',
        ),
        migrations.RemoveField(
            model_name='component',
            name='year',
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='data_range_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='data_range_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.datapoint'),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('graph', 'graph')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=50),
        ),
    ]
