# Generated by Django 4.2.6 on 2024-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0021_remove_component_data_range_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='data_type',
            new_name='input_type',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red'), ('blue', 'blue')], max_length=50),
        ),
    ]
