# Generated by Django 4.2.6 on 2024-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0022_rename_data_type_component_input_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='input_type',
            new_name='inout_type',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('red', 'red'), ('green', 'green')], max_length=50),
        ),
    ]
