# Generated by Django 4.2.6 on 2024-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0023_rename_input_type_component_inout_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='inout_type',
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('graph', 'graph'), ('card', 'card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=50),
        ),
    ]
