# Generated by Django 4.2.6 on 2024-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0024_remove_component_inout_type_alter_component_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='data_type',
            field=models.CharField(blank=True, choices=[('year', 'year'), ('month', 'month'), ('quarter', 'quarter')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('graph', 'graph')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('blue', 'blue'), ('red', 'red')], max_length=50),
        ),
    ]
