# Generated by Django 4.2.6 on 2024-09-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0026_remove_component_configuration_component_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('graph', 'graph')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red')], max_length=50),
        ),
    ]
