# Generated by Django 4.2.6 on 2024-09-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0026_remove_component_configuration_component_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('blue', 'blue'), ('red', 'red')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
