# Generated by Django 4.2.6 on 2024-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0027_dashboardindicator_rank_dashboardindicator_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('table', 'table'), ('graph', 'graph')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red'), ('green', 'green')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardindicator',
            name='width',
            field=models.CharField(blank=True, choices=[('25%', '25%'), ('33%', '33%'), ('50%', '50%'), ('100%', '100%')], default='50%', max_length=50, null=True),
        ),
    ]
