# Generated by Django 4.2.6 on 2024-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0028_alter_component_category_alter_dashboard_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='has_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='has_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('graph', 'graph'), ('table', 'table')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red')], max_length=50, null=True),
        ),
    ]
