# Generated by Django 4.2.6 on 2024-10-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0029_component_has_description_component_has_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardindicator',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('graph', 'graph'), ('card', 'card'), ('table', 'table')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=50, null=True),
        ),
    ]
