# Generated by Django 4.2.6 on 2024-10-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_quarterdata_indicator'),
        ('DashBoard', '0030_dashboardindicator_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('graph', 'graph'), ('table', 'table')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('blue', 'blue'), ('red', 'red')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardindicator',
            name='data_range_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dateEndDataPoint', to='Base.datapoint'),
        ),
        migrations.AlterField(
            model_name='dashboardindicator',
            name='data_range_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dateStartDataPoint', to='Base.datapoint'),
        ),
    ]
