# Generated by Django 4.2.6 on 2024-10-22 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0033_alter_component_category_alter_dashboard_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('table', 'table'), ('graph', 'graph'), ('card', 'card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('blue', 'blue'), ('red', 'red')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='for_dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='DashBoard.dashboard'),
        ),
    ]
