# Generated by Django 4.2.6 on 2024-10-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0034_alter_component_category_alter_dashboard_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('table', 'table'), ('card', 'card'), ('graph', 'graph')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardindicator',
            name='for_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cols', to='DashBoard.row'),
        ),
    ]
