# Generated by Django 4.2.6 on 2024-10-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0036_alter_component_category_alter_component_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='has_indicator',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('table', 'table'), ('card', 'card'), ('graph', 'graph')], max_length=50),
        ),
    ]
