# Generated by Django 4.2.6 on 2024-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_quarterdata_indicator'),
        ('DashBoard', '0037_component_has_indicator_alter_component_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('graph', 'graph'), ('table', 'table')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('red', 'red'), ('blue', 'blue')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardindicator',
            name='indicator',
            field=models.ManyToManyField(blank=True, related_name='indicator', to='Base.indicator'),
        ),
    ]
