# Generated by Django 4.2.6 on 2024-11-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0039_alter_dashboardindicator_options_row_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('table', 'table'), ('graph', 'graph')], max_length=50),
        ),
        migrations.AlterField(
            model_name='row',
            name='style',
            field=models.CharField(choices=[('justify-content-end', 'End'), ('justify-content-center', 'Center'), ('justify-content-between', 'Gap between'), ('justify-content-start', 'Start')], default='justify-content-start', max_length=100),
        ),
    ]
