# Generated by Django 4.2.6 on 2024-11-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0039_component_has_json_component_json_and_more'),
        ('DashBoard', '0040_alter_component_category_alter_row_style'),
    ]

    operations = [
    ]
