# Generated by Django 4.2.6 on 2024-11-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0041_merge_20241106_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('graph', 'graph'), ('table', 'table'), ('card', 'card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='style',
            field=models.CharField(choices=[('justify-content-start', 'Start'), ('justify-content-between', 'Gap between'), ('justify-content-end', 'End'), ('justify-content-center', 'Center')], default='justify-content-start', max_length=100),
        ),
    ]
