# Generated by Django 4.2.6 on 2024-11-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0043_alter_row_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addis_ababa', models.FloatField(blank=True, null=True)),
                ('tigray', models.FloatField(blank=True, null=True)),
                ('amhara', models.FloatField(blank=True, null=True)),
                ('oromia', models.FloatField(blank=True, null=True)),
                ('somali', models.FloatField(blank=True, null=True)),
                ('afar', models.FloatField(blank=True, null=True)),
                ('benshangul_gumuz', models.FloatField(blank=True, null=True)),
                ('dire_dawa', models.FloatField(blank=True, null=True)),
                ('gambella', models.FloatField(blank=True, null=True)),
                ('snnp', models.FloatField(blank=True, null=True)),
                ('harari', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('blue', 'blue'), ('red', 'red')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='style',
            field=models.CharField(choices=[('justify-content-end', 'End'), ('justify-content-between', 'Gap between'), ('justify-content-center', 'Center'), ('justify-content-start', 'Start')], default='justify-content-start', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashBoard.regions'),
        ),
    ]
