# Generated by Django 4.2.6 on 2024-11-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0045_alter_component_category_alter_dashboard_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardindicator',
            name='regions',
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='addis_ababa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='afar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='amhara',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='benshangul_gumuz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='dire_dawa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='gambella',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='harari',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='oromia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='snnp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='somali',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='tigray',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('card', 'card'), ('graph', 'graph'), ('table', 'table')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('blue', 'blue'), ('red', 'red')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='style',
            field=models.CharField(choices=[('justify-content-center', 'Center'), ('justify-content-between', 'Gap between'), ('justify-content-start', 'Start'), ('justify-content-end', 'End')], default='justify-content-start', max_length=100),
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
    ]
