# Generated by Django 4.2.6 on 2024-11-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0049_alter_component_category_alter_dashboard_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardindicator',
            name='custom_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='dashboardindicator',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('table', 'table'), ('graph', 'graph'), ('card', 'card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='row',
            name='style',
            field=models.CharField(choices=[('justify-content-end', 'End'), ('justify-content-center', 'Center'), ('justify-content-start', 'Start'), ('justify-content-between', 'Gap between')], default='justify-content-start', max_length=100),
        ),
    ]
