# Generated by Django 4.2.6 on 2024-11-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0052_alter_row_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='has_image',
            new_name='is_image_component',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red'), ('green', 'green')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='style',
            field=models.CharField(choices=[('justify-content-between', 'Gap between'), ('justify-content-center', 'Center'), ('justify-content-start', 'Start'), ('justify-content-end', 'End')], default='justify-content-start', max_length=100),
        ),
    ]
