# Generated by Django 4.2.6 on 2025-05-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiledahboardoverview',
            old_name='icon',
            new_name='backgroung_image',
        ),
    ]
