# Generated by Django 4.2.6 on 2025-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_rename_icon_mobiledahboardoverview_backgroung_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledahboardoverview',
            name='is_tranding',
            field=models.BooleanField(default=False),
        ),
    ]
