# Generated by Django 4.2.6 on 2025-05-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_mobiledahboardoverview_is_tranding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiledahboardoverview',
            old_name='backgroung_image',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='mobiledahboardoverview',
            old_name='is_tranding',
            new_name='is_trending',
        ),
    ]
