# Generated by Django 4.2.6 on 2025-05-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_monthdata_options_alter_quarterdata_options'),
        ('mobile', '0004_rename_backgroung_image_mobiledahboardoverview_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledahboardoverview',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.month'),
        ),
    ]
