# Generated by Django 4.2.6 on 2025-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_mobile_dashaboard_overview',
            field=models.BooleanField(default=False),
        ),
    ]
