# Generated by Django 4.2.6 on 2024-09-05 11:47

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
