# Generated by Django 4.2.6 on 2025-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_topic_is_mobile_dashaboard_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='media/background_image'),
        ),
    ]
