# Generated by Django 4.2.6 on 2024-09-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_category_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualdata',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_data', to='Base.indicator'),
        ),
    ]
