# Generated by Django 4.2.6 on 2024-09-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_topic_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='kpi_characteristics',
            field=models.CharField(blank=True, choices=[('inc', 'Increasing'), ('dec', 'Decreasing'), ('const', 'Constant')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='measurement_units',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
