# Generated by Django 4.2.6 on 2024-09-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_annualdata_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterdata',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarter_data', to='Base.indicator'),
        ),
    ]
