# Generated by Django 4.2.6 on 2025-05-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_topic_background_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthdata',
            options={'ordering': ['-for_datapoint__year_EC']},
        ),
        migrations.AlterModelOptions(
            name='quarterdata',
            options={'ordering': ['-for_datapoint__year_EC']},
        ),
    ]
